#!/bin/bash
PUPPET_REPO="https://github.com/bitfield/dt-demo.git"
if [ "$#" -lt 2 ]; then
  cat <<USAGE
Usage: $0 TARGET [BRANCH]
Install Puppet on the node TARGET (IP address or DNS name) and run 
the bootstrap process, and optionally use the control repo branch BRANCH.
USAGE
  exit 1
fi
TARGET=$1
BRANCH=${2:-production}
OPTIONS="-oStrictHostKeyChecking=no"
echo -n "Copying bootstrap script... "
scp ${OPTIONS} $(dirname $0)/bootstrap.sh ${TARGET}:/tmp
echo "done."
echo -n "Bootstrapping... "
ssh ${OPTIONS} ${TARGET} "sudo bash /tmp/bootstrap.sh ${PUPPET_REPO} ${BRANCH}"
echo "done."
